# Generated by Django 4.2 on 2023-05-22 17:36

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_tweetimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.reply_upload_to),
        ),
    ]
