# Generated by Django 4.2 on 2023-05-12 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_reaction_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyreaction',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.reply'),
        ),
    ]
